# rideshare-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rideshare-service-secrets
  namespace: rideshare-prod
type: Opaque
stringData:
  DATABASE_URL: "postgresql://rideshare_user:strongpassword123@postgres-primary:5432/rideshare?sslmode=disable"
  JWT_SECRET: "123456789"