apiVersion: apps/v1
kind: Deployment
metadata:
  name: rideshare-driver
  namespace: rideshare-prod
  labels:
    app: rideshare-driver
spec:
  selector:
    matchLabels:
      app: rideshare-driver
  template:
    metadata:
      labels:
        app: rideshare-driver
    spec:
      containers:
        - name: rideshare-driver
          image: 221693237976.dkr.ecr.us-east-2.amazonaws.com/jibike_rideshare_rider_service:rideshare-driver-service-v0.10
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - secretRef:
                name: rideshare-secrets