apiVersion: v1
kind: Service
metadata:
  name: rideshare-driver
  namespace: rideshare-prod
spec:
  type: ClusterIP   # Only accessible within the cluster
  selector:
    app: rideshare-driver
  ports:
    - protocol: TCP
      port: 3003       # The port other pods/services will use to reach this service
      targetPort: 3003 # The port your container is listening on