apiVersion: v1
kind: Service
metadata:
  name: matching-service
spec:
  type: ClusterIP   # Only accessible within the cluster
  selector:
    app: matching-service
  ports:
    - protocol: TCP
      port: 3004       # The port other pods/services will use to reach this service
      targetPort: 3004 # The port your container is listening on