name: e-commerce-infrastructure-aws infrastructure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  aws-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::221693237976:role/github-actions-oidc-jibike
          aws-region: us-east-2

      - name: Test AWS Access
        run: aws sts get-caller-identity