name: "Terraform Infrastructure Pipeline"
run-name: "${{ github.event.inputs.action }} → ${{ github.event.inputs.terraform_folder }} (${{ github.event.inputs.environment }})"

on:
  workflow_dispatch:
    inputs:
      terraform_folder:
        description: "Select Terraform module"
        required: true
        type: choice
        options:
          - vpc
          - eks
          - eks-dependency
          - ec2
          - rds
          - redis
          - s3

      action:
        description: "Select action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.event.inputs.terraform_folder }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      # 🔐 AWS OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: arn:aws:iam::221693237976:role/github-actions-oidc-jibike
          aws-region: us-east-1

      - name: Login to AWS Public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 \
          | helm registry login \
            --username AWS \
            --password-stdin public.ecr.aws

      - name: Show Deployment Context
        run: |
          echo "🚀 Terraform Deployment"
          echo "Folder: ${{ github.event.inputs.terraform_folder }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Action: ${{ github.event.inputs.action }}"

      # 🛠 Terraform Install
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 #v4

      # 📦 Init with backend
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=jibike-teleios-state-file" \
            -backend-config="key=${{ github.event.inputs.terraform_folder }}/${{ github.event.inputs.environment }}.tfstate" \
            -backend-config="region=us-east-1"

      # 🔎 Validate
      - name: Terraform Validate
        run: terraform validate

      # 📋 PLAN
      - name: Terraform Plan
        if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
        run: terraform plan --var-file=${{ github.event.inputs.environment }}.tfvars -out=tfplan

      # 🚀 APPLY
      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply --var-file=${{ github.event.inputs.environment }}.tfvars -auto-approve tfplan

      # 💣 DESTROY
      - name: Terraform Destroy Plan
        if: github.event.inputs.action == 'destroy'
        run: |
          terraform plan -destroy -out=tfdestroyplan \
            --var-file=${{ github.event.inputs.environment }}.tfvars

      - name: Terraform Destroy Apply
        if: github.event.inputs.action == 'destroy'
        run: terraform apply -auto-approve tfdestroyplan