name: "Terraform Infrastructure Pipeline"

on:
  workflow_dispatch:
    inputs:
      terraform_folder:
        description: "Select Terraform module"
        required: true
        type: choice
        options:
          - vpc
          - eks
          - ec2
          - rds
          - redis
          - s3

      action:
        description: "Select action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.event.inputs.terraform_folder }}

    env:
      TF_WORKSPACE: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      # 🔐 AWS OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: arn:aws:iam::221693237976:role/github-actions-oidc-jibike
          aws-region: us-east-1

      # 🛠 Terraform Install
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 #v4

      # 📦 Init with backend
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=jibike-teleios-state-file" \
            -backend-config="key=${{ github.event.inputs.terraform_folder }}/${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=us-east-1"

      # 🌍 Workspace Handling
      - name: Select or Create Workspace
        run: |
          terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE

      # 🔎 Validate
      - name: Terraform Validate
        run: terraform validate

      # 📋 PLAN
      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        run: terraform plan -out=tfplan

      # 🚀 APPLY
      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      # 💣 DESTROY
      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve